[package]
name = "hyprfetch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "hyprfetch"
path = "src/main.rs"

[dependencies]
hyprfetch-core = { path = "../hyprfetch-core" }
hyprfetch-db = { path = "../hyprfetch-db" }
hyprfetch-api = { path = "../hyprfetch-api" }

tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
